# 配置数据源
spring:
  datasource:
    url: "jdbc:mysql://8.141.83.81/main"
    username: "root"
    password: "english_improver"
    driver-class-name: com.mysql.cj.jdbc.Driver
# 配置mybatis
mybatis:
  mapper-locations: classpath:com/ei/mapper/*.xml
  type-aliases-package: com.ei.entities